farmergame/urls.py
from django.urls import path

from . import views

app_name='farmergame'
urlpatterns = [
    path('', views.root, name='root'),
    path('index/', views.FarmListView.as_view(), name='index'),
    path('<int:pk>/',views.view_farm, name='view_farm'),
    path('<int:pk>/buy/',views.trade_animals, name='trade_animals'),
    path('<int:pk>/button', views.button_trade , name='button_trade')
]

mysite/farmergame/urls.py
from django.urls import path

from . import views

app_name='farmergame'
urlpatterns = [
    path('', views.root, name='root'),
    path('index/', views.FarmListView.as_view(), name='index'),
    path('<int:pk>/',views.view_farm, name='view_farm'),
    path('<int:pk>/buy/',views.trade_animals, name='trade_animals'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('polls/',include('polls.urls')),
    path('farmergame/',include('farmergame.urls')),
    path('admin/', admin.site.urls),
]

polls/urls.py
from django.urls import path

from . import views

app_name = 'polls'
urlpatterns = [
    # ex: /polls/
    path('', views.IndexView.as_view(),name='index'),
    # ex: /polls/5
    path('<int:pk>/',views.DetailView.as_view(),name='detail'),
    # ex: /polls/5/results
    path('<int:pk>/results/',views.ResultsView.as_view(), name='results'),
    # ex: /polls/5/vote
    path('<int:question_id>/vote/',views.vote, name='vote')
]

farmergame/models.py
from django.db import models
import numpy as np
# Create your models here.
    

class Animal(models.Model):
    species = models.CharField(max_length=255)
    breed = models.CharField(max_length=255)
    buy_price = models.IntegerField(default=0)
    sell_price = models.IntegerField(default=0)
    benefits = models.FloatField(default=0)
    
    def __str__(self):
        return self.species + ": " + self.breed


class AnnualCrop(models.Model):
    type = models.CharField(max_length = 100)
    specifics = models.CharField(max_length = 255)
    seed_price = models.IntegerField(default=0)
    sell_price = models.IntegerField(default=0)

class Person(models.Model):
    name = models.CharField(max_length = 100)
    age = models.IntegerField(default = 0)
    school_years = models.IntegerField(default = 0)

    
    
class Farm(models.Model):

    fields = np.zeros([3,3],dtype=int)
    
    name = models.CharField(max_length=200)
    money = models.IntegerField(default=4000)
    animals = models.ManyToManyField(Animal, through='OwnAnimal')
      
    def __str__(self):
        return self.name

class OwnAnimal(models.Model):
    farm = models.ForeignKey(Farm, on_delete=models.CASCADE)
    animal = models.ForeignKey(Animal, on_delete=models.CASCADE)
    nr_owned = models.IntegerField(default=0)
    
    def __str__(self):
        return str(self.nr_owned) + " " + str(self.animal) + " on farm: " + str(self.farm)

mysite/farmergame/models.py
from django.db import models
import numpy as np
# Create your models here.
    

class Animal(models.Model):
    species = models.CharField(max_length=255)
    breed = models.CharField(max_length=255)
    buy_price = models.IntegerField(default=0)
    sell_price = models.IntegerField(default=0)
    benefits = models.FloatField(default=0)
    
    def __str__(self):
        return self.species + ": " + self.breed


class AnnualCrop(models.Model):
    type = models.CharField(max_length = 100)
    specifics = models.CharField(max_length = 255)
    seed_price = models.IntegerField(default=0)
    sell_price = models.IntegerField(default=0)

class Person(models.Model):
    name = models.CharField(max_length = 100)
    age = models.IntegerField(default = 0)
    school_years = models.IntegerField(default = 0)

    
    
class Farm(models.Model):

    fields = np.zeros([3,3],dtype=int)
    
    name = models.CharField(max_length=200)
    capital = models.IntegerField(default=4000)
    animals = models.ManyToManyField(Animal, through='OwnAnimal')
      
    def __str__(self):
        return self.name

class OwnAnimal(models.Model):
    farm = models.ForeignKey(Farm, on_delete=models.CASCADE)
    animal = models.ForeignKey(Animal, on_delete=models.CASCADE)
    nr_owned = models.IntegerField(default=0)
    
    def __str__(self):
        return str(self.nr_owned) + " " + str(self.animal) + " on farm: " + str(self.farm)

farmergame/forms.py
from django import forms
from django.shortcuts import get_object_or_404

from .models import Farm, Animal, OwnAnimal

class FarmForm(forms.ModelForm):
    class Meta:
        model = Farm
        fields = ['name','animals','money']
        
    animals = forms.ModelMultipleChoiceField(
        queryset=Animal.objects.all(),
        widget = forms.CheckboxSelectMultiple
    )


class TradeAnimalsForm(forms.Form):
    
    def __init__(self, farm_pk, *args, **kwargs):
        super(TradeAnimalsForm,self).__init__(*args, **kwargs)
        self.owned_animals = Farm.objects.get(pk=farm_pk).ownanimal_set.all().order_by('animal__buy_price')
    
        for owned_animal in self.owned_animals:
            field_name = str(owned_animal.pk)
            self.fields[field_name] = forms.IntegerField(initial=owned_animal.nr_owned)
            self.fields[field_name].label = "Number of %ss" %owned_animal.animal.species

mysite/farmergame/forms.py
from django import forms
from django.shortcuts import get_object_or_404

from .models import Farm, Animal, OwnAnimal

class FarmForm(forms.ModelForm):
    class Meta:
        model = Farm
        fields = ['name','animals','capital']
        
    animals = forms.ModelMultipleChoiceField(
        queryset=Animal.objects.all(),
        widget = forms.CheckboxSelectMultiple
    )


class TradeAnimalsForm(forms.Form):
    
    def __init__(self, farm_pk, *args, **kwargs):
        super(TradeAnimalsForm,self).__init__(*args, **kwargs)
        self.owned_animals = Farm.objects.get(pk=farm_pk).ownanimal_set.all().order_by('nr_owned')
    
        for owned_animal in self.owned_animals:
            field_name = str(owned_animal.pk)
            self.fields[field_name] = forms.IntegerField(initial=owned_animal.nr_owned)
            self.fields[field_name].label = "Number of %ss" %owned_animal.animal.species

farmergame/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.views import generic
from django.forms import modelformset_factory
from django.core.serializers.json import DjangoJSONEncoder
from json import dumps

from .models import Animal, Farm, OwnAnimal
from .forms import TradeAnimalsForm

class FarmListView(generic.ListView):
    """The view for the index of farms"""
    model = Farm
    template_name='farmergame/farm_list.html'

def root(request):
    """the root page"""
    return render(request, 'farmergame/base_farmergame.html')


def trade_animals(request, pk):
    """handles the buy animals form page"""
    farm = get_object_or_404(Farm, pk=pk)
    #create a formset
    #TradeFormSet = modelformset_factory(OwnAnimal,
     #                                   fields = ('nr_owned',),
      #                                  labels = {'nr_owned':'desired number of %ss' %} )
    
    #formset = TradeFormSet(queryset=OwnAnimal.objects.filter(farm__pk=pk))
    if request.method == 'POST':
        form = TradeAnimalsForm(pk, request.POST)
        #create an instance of BuyAnimalsForm and populate it 
        if form.is_valid():
            farm = Farm.objects.get(pk=pk)
            owned_animals = farm.ownanimal_set.all()
            money = farm.money
            
            for owned_animal in owned_animals:
                nr_change = form.cleaned_data[str(owned_animal.pk)] - owned_animal.nr_owned
                
                if nr_change > 0:
                    #we buy animals
                    print("Buying: ", nr_change, " ", owned_animal.animal.species)
                    money -= owned_animal.animal.buy_price*(nr_change)
                else:
                    print("Selling: ",-nr_change," ", owned_animal.animal.species)
                    money -=  owned_animal.animal.sell_price*(nr_change)
            
            if (money > 0):
                print("Trade successful!")
                for owned_animal in owned_animals:
                    owned_animal.nr_owned = form.cleaned_data[str(owned_animal.pk)]
                    owned_animal.save()
                
                farm.capital = money
                farm.save()
                
                return HttpResponseRedirect(reverse('farmergame:view_farm',args=(farm.id,)))
                
            return render(request, 'farmergame/buy_animals.html', {'farm': farm,
                                                                    'form': form,
                                                                    'error_message':"Not enough money! need %d more" %-money})
    else:
        form = TradeAnimalsForm(pk)
        return render(request, 'farmergame/buy_animals.html', {'farm': farm, 'form': form})
        
def button_trade(request, pk):
    print("Button trade working!")
    #button = request.GET.get('button', None)
    #print(button)
    response = render(request, 'farmergame/buy_animals.html', {
        'farm': get_object_or_404(Farm, pk=1),
        'form': TradeAnimalsForm(1)
    })
    return response

def view_farm(request, pk):
    """view the farm"""
    farm = get_object_or_404(Farm, pk=pk)
    return render(request, 'farmergame/view_farm.html', {
        'farm':farm
    })

mysite/farmergame/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.views import generic
from django.forms import modelformset_factory
from django.core.serializers.json import DjangoJSONEncoder
from json import dumps

from .models import Animal, Farm, OwnAnimal
from .forms import TradeAnimalsForm

class FarmListView(generic.ListView):
    """The view for the index of farms"""
    model = Farm
    template_name='farmergame/farm_list.html'

def root(request):
    """the root page"""
    return render(request, 'farmergame/base_farmergame.html')


def trade_animals(request, pk):
    """handles the buy animals form page"""
    farm = get_object_or_404(Farm, pk=pk)
    #create a formset
    #TradeFormSet = modelformset_factory(OwnAnimal,
     #                                   fields = ('nr_owned',),
      #                                  labels = {'nr_owned':'desired number of %ss' %} )
    
    #formset = TradeFormSet(queryset=OwnAnimal.objects.filter(farm__pk=pk))
    if request.method == 'POST':
        form = TradeAnimalsForm(pk, request.POST)
        #create an instance of BuyAnimalsForm and populate it 
        if form.is_valid():
            farm = Farm.objects.get(pk=pk)
            owned_animals = farm.ownanimal_set.all()
            money = farm.capital
            
            for owned_animal in owned_animals:
                nr_change = form.cleaned_data[str(owned_animal.pk)] - owned_animal.nr_owned
                
                if nr_change > 0:
                    #we buy animals
                    print("Buying: ", nr_change, " ", owned_animal.animal.species)
                    money -= owned_animal.animal.buy_price*(nr_change)
                else:
                    print("Selling: ",-nr_change," ", owned_animal.animal.species)
                    money -=  owned_animal.animal.sell_price*(nr_change)
            
            if (money > 0):
                print("Trade successful!")
                for owned_animal in owned_animals:
                    owned_animal.nr_owned = form.cleaned_data[str(owned_animal.pk)]
                    owned_animal.save()
                
                farm.capital = money
                farm.save()
                
                return HttpResponseRedirect(reverse('farmergame:view_farm',args=(farm.id,)))
                
            return render(request, 'farmergame/buy_animals.html', {'farm': farm,
                                                                    'form': form,
                                                                    'error_message':"Not enough money! need %d more" %-money})
    else:
        form = TradeAnimalsForm(pk)
        return render(request, 'farmergame/buy_animals.html', {'farm': farm, 'form': form})
        
def view_farm(request, pk):
    """view the farm"""
    farm = get_object_or_404(Farm, pk=pk)
    return render(request, 'farmergame/view_farm.html', {
        'farm':farm
    })

farmergame/templates/farmergame/base_farmergame.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    {% load static %}
    <link rel="stylesheet" , type="text/css" href="{% static 'farmergame/style.css' %}">
    <link rel="shortcut icon" href="{% static 'farmergame/images/favicon.png' %}"/>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script>
    $(document).ready(function () {
        /*$("a").click(function(){
            alert("you clicked " + $(this).text())
        });*/
        
        $("#buy").click(function(){
            alert("you clikckdaen buy button")
            let AJdata = { 'button': $(this).text() }
            $.ajax({
                data: AJdata,
                url: "{% url 'farmergame:button_trade' 1 %}",
                //on success
                success: function(response) {
                    $("#content").html(response)
                },
    
                error: function(response) {
                    console.log(response.errors)
                }
            });
        });
        
    });
    </script>
    <title>{% block title %}The Farmer game{% endblock %}</title>
</head>

<body>
    <!-- The sidebar -->
    <div class="sidebar">
        {% block sidebar %}
        <a class="active" href="#home">Overview</a>
        <a id="buy" href="#buy">buy animals</a>
        <a href="#contact">Contact</a>
        <a href="#about">About</a>
        more sidebar stuff!
        {% endblock sidebar %}
    </div>

    <!-- Page content -->
    <div class="content">
        {% block header %}
        <h1 id='demo'>Default stuff here</h1>
        {% endblock %}
        <div id="content"></div>
        {% block content %}
        <h1>Welcome to the farmer game!</h1>
        <p>more stuff will be implemented</p>
        <a href="{% url 'farmergame:index' %}">Go to the farm index</a>
        {% endblock content %}
        </div>
    </div>
</body>

</html>

farmergame/templates/farmergame/buy_animals.html
    <h1>Trade animals for {{ farm.name }}</h1>
    {% if error_message %}
        <strong>{{ error_message }}</strong>
    {% endif %}
    <div>
        <form method="POST">
            {% csrf_token %}
            <table>
            {% for field in form %}
            <tr>
                <td>{{ field.label }}</td>
                <td>{{ field }}</td>
                <td>meeer peop!</td>
            <tr>
            {% endfor %}
            
            </table>
            <input type="submit" value="Confirm"/>
        </form>
    </div>

farmergame/templates/farmergame/farm_list.html
{% extends "farmergame/base_farmergame.html" %}
{% block title %} Farm list view {% endblock %}
{% block content %}
    <h1>Farms</h1>
    <ul>
        {% for farm in object_list %}
            <li><a href="{% url 'farmergame:view_farm' farm.id %}"> {{ farm.name }} - {{ farm.capital }}</a></li>
        {% empty %}
            <li>No farms yet.</li>
        {% endfor %}
    </ul>
{% endblock content %}

farmergame/templates/farmergame/view_farm.html
{% extends "farmergame/base_farmergame.html" %}
{% block title %}Farm view: {{ farm.name }}{% endblock %}
{% load static %}
{% block content %}
    <h1>{{ farm.name }}</h1>
    Money: {{ farm.capital }}<br>
    <a href="{% url 'farmergame:trade_animals' farm.pk %}">Trade animals!</a>
    
    <ul>
        {% for ownanimal in farm.ownanimal_set.all %}
            <li>{{ownanimal.nr_owned}} {{ ownanimal.animal.species }}s of breed {{ ownanimal.animal.breed }}</li>
        {% empty %}
            <li>No animals available.</li>
        {% endfor %}
    </ul>
    
    <h2 id='all_data'> hello {{ farm.ownanimal_set.all }} </h2>
{% endblock content %}